# Copyright 2024 TsumiNa.
# SPDX-License-Identifier: Apache-2.0

__all__ = [
    "BaseRunner",
    "BaseLRScheduler",
    "BaseOptimizer",
    "BaseExtension",
    "Checker",
    "ClipNorm",
    "ClipValue",
    "NLLLoss",
    "L1Loss",
    "MSELoss",
    "CrossEntropyLoss",
    "CTCLoss",
    "PoissonNLLLoss",
    "KLDivLoss",
    "BCELoss",
    "BCEWithLogitsLoss",
    "MarginRankingLoss",
    "HingeEmbeddingLoss",
    "MultiLabelMarginLoss",
    "SmoothL1Loss",
    "SoftMarginLoss",
    "MultiLabelSoftMarginLoss",
    "CosineEmbeddingLoss",
    "MultiMarginLoss",
    "TripletMarginLoss",
    "TripletMarginWithDistanceLoss",
    "ArrayDataset",
    "CrystalGraphDataset",
    "LambdaLR",
    "StepLR",
    "MultiStepLR",
    "ExponentialLR",
    "CosineAnnealingLR",
    "ReduceLROnPlateau",
    "CyclicLR",
    "Adadelta",
    "Adagrad",
    "Adam",
    "Adamax",
    "ASGD",
    "SGD",
    "SparseAdam",
    "RMSprop",
    "Rprop",
    "LBFGS",
    "Trainer",
]


from torch.nn.modules.loss import (
    BCELoss,
    BCEWithLogitsLoss,
    CosineEmbeddingLoss,
    CrossEntropyLoss,
    CTCLoss,
    HingeEmbeddingLoss,
    KLDivLoss,
    L1Loss,
    MarginRankingLoss,
    MSELoss,
    MultiLabelMarginLoss,
    MultiLabelSoftMarginLoss,
    MultiMarginLoss,
    NLLLoss,
    PoissonNLLLoss,
    SmoothL1Loss,
    SoftMarginLoss,
    TripletMarginLoss,
    TripletMarginWithDistanceLoss,
)

from shotgun_csp.model.training.base import BaseExtension, BaseLRScheduler, BaseOptimizer, BaseRunner
from shotgun_csp.model.training.checker import Checker
from shotgun_csp.model.training.clip_grad import ClipNorm, ClipValue
from shotgun_csp.model.training.dataset import ArrayDataset, CrystalGraphDataset
from shotgun_csp.model.training.lr_scheduler import (
    CosineAnnealingLR,
    CyclicLR,
    ExponentialLR,
    LambdaLR,
    MultiStepLR,
    ReduceLROnPlateau,
    StepLR,
)
from shotgun_csp.model.training.optimizer import (
    ASGD,
    LBFGS,
    SGD,
    Adadelta,
    Adagrad,
    Adam,
    Adamax,
    RMSprop,
    Rprop,
    SparseAdam,
)
from shotgun_csp.model.training.trainer import Trainer
